#!/usr/bin/env sh
REST=$@
EXP_DIR="/home/fdila/"

rosrun phaser_core phaser_core_driver \
  --v=3 \
  --alsologtostderr=1 \
  --registration_algorithm="sph-opt-multiple" \
  --target_cloud="${EXP_DIR}target.ply" \
  --source_cloud="${EXP_DIR}source.ply" \
  --reg_cloud="${EXP_DIR}registered" \
  --phaser_core_spherical_bandwidth=2 \
  --phaser_core_spherical_low_pass_lower_bound=000 \
  --phaser_core_spherical_low_pass_upper_bound=100 \
  --phaser_core_spherical_zero_padding=0 \
  --phaser_core_spatial_n_voxels=10 \
  --phaser_core_spatial_discretize_lower=-50 \
  --phaser_core_spatial_discretize_upper=50 \
  --phaser_core_spatial_low_pass_lower_bound=0 \
  --phaser_core_spatial_low_pass_upper_bound=150 \
  --phaser_core_spatial_zero_padding=0 \
  --gaussian_peak_neighbors=4 \
  --bingham_peak_neighbors_radius=0 \
  --phaser_pre_enable_geometric_cloud_segmentation=false \
  --visualize_correlation=false \
  --dump_correlation_to_file=true \
  $REST
